// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExJGWTLkNSIBBVKIhdUPeC3clJTeVue0',
    appId: '1:225573553200:web:a53db15099d7a2da9ed9f5',
    messagingSenderId: '225573553200',
    projectId: 'beesaving-stuapp-2026',
    authDomain: 'beesaving-stuapp-2026.firebaseapp.com',
    storageBucket: 'beesaving-stuapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF90NUFtbntbsH4QwmMeqwHtciPnaMs_8',
    appId: '1:225573553200:android:1c8ff182c8f2081b9ed9f5',
    messagingSenderId: '225573553200',
    projectId: 'beesaving-stuapp-2026',
    storageBucket: 'beesaving-stuapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5v64wb5tyfEpWPBbHvUtk9TJyM_RoWAI',
    appId: '1:225573553200:ios:e2f9703e6de815649ed9f5',
    messagingSenderId: '225573553200',
    projectId: 'beesaving-stuapp-2026',
    storageBucket: 'beesaving-stuapp-2026.firebasestorage.app',
    iosBundleId: 'com.beesaving.beesaving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5v64wb5tyfEpWPBbHvUtk9TJyM_RoWAI',
    appId: '1:225573553200:ios:e2f9703e6de815649ed9f5',
    messagingSenderId: '225573553200',
    projectId: 'beesaving-stuapp-2026',
    storageBucket: 'beesaving-stuapp-2026.firebasestorage.app',
    iosBundleId: 'com.beesaving.beesaving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBExJGWTLkNSIBBVKIhdUPeC3clJTeVue0',
    appId: '1:225573553200:web:b28013a0bc7110ef9ed9f5',
    messagingSenderId: '225573553200',
    projectId: 'beesaving-stuapp-2026',
    authDomain: 'beesaving-stuapp-2026.firebaseapp.com',
    storageBucket: 'beesaving-stuapp-2026.firebasestorage.app',
  );
}
